// Mock data for development and demo purposes

export interface MockVideo {
  id: number
  title: string
  description: string
  thumbnailUrl?: string
  videoUrl?: string
  category?: string
  tags?: string[]
  views: number
  likes: number
  viewCount?: number
  likeCount?: number
  duration: number
  createdAt: string
  userId: number
  userName: string
  isPublic: boolean
}

export interface MockUser {
  id: number
  name: string
  email: string
}

export interface MockComment {
  id: number
  content: string
  userId: number
  userName: string
  createdAt: string
  likes: number
}

// Sample video URLs for demonstration
const sampleVideoUrls = [
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
  'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
  'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_2mb.mp4',
  'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_5mb.mp4',
  'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_10mb.mp4',
  'https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_1mb.mp4',
  'https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_2mb.mp4',
  'https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_5mb.mp4',
  'https://sample-videos.com/video123/mp4/480/big_buck_bunny_480p_10mb.mp4',
  'https://sample-videos.com/video123/mp4/360/big_buck_bunny_360p_1mb.mp4',
  'https://sample-videos.com/video123/mp4/360/big_buck_bunny_360p_2mb.mp4',
]

// Mock videos data
export const mockVideos: MockVideo[] = [
  {
    id: 1,
    title: '製造業の基礎技術 - 溶接の基本',
    description: '熟練技術者が教える溶接の基本技術と安全対策について詳しく解説します。',
    category: '製造業',
    tags: ['技術', '溶接', '安全'],
    views: 1250,
    likes: 45,
    duration: 1200,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 1,
    userName: '技術者 太郎',
    isPublic: true,
    viewCount: 1250,
    likeCount: 45,
    videoUrl: sampleVideoUrls[0],
    thumbnailUrl: `https://picsum.photos/seed/video1/640/360`,
  },
  {
    id: 2,
    title: '多言語対応の重要性 - 外国人労働者への教育',
    description: '多様な言語背景を持つ労働者への効果的な教育方法を紹介します。',
    category: '教育',
    tags: ['教育', '多言語', 'コミュニケーション'],
    views: 890,
    likes: 32,
    duration: 900,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 2,
    userName: '教育者 花子',
    isPublic: true,
    viewCount: 890,
    likeCount: 32,
    videoUrl: sampleVideoUrls[1 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video2/640/360`,
  },
  {
    id: 3,
    title: '品質管理のベストプラクティス',
    description: '製造現場での品質管理の実践的な方法を解説します。',
    category: '製造業',
    tags: ['品質管理', '製造', 'ベストプラクティス'],
    views: 2100,
    likes: 78,
    duration: 1500,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 3,
    userName: '品質管理者 次郎',
    isPublic: true,
    viewCount: 2100,
    likeCount: 78,
    videoUrl: sampleVideoUrls[2 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video3/640/360`,
  },
  {
    id: 4,
    title: '安全作業の基本 - 個人保護具の正しい使い方',
    description: '作業現場での安全を守るための個人保護具の正しい使用方法を説明します。',
    category: '安全',
    tags: ['安全', '個人保護具', '作業'],
    views: 1560,
    likes: 56,
    duration: 800,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 1,
    userName: '技術者 太郎',
    isPublic: true,
    viewCount: 1560,
    likeCount: 56,
    videoUrl: sampleVideoUrls[3 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video4/640/360`,
  },
  {
    id: 5,
    title: '機械メンテナンスの基礎',
    description: '製造機械の日常メンテナンスとトラブルシューティングの方法を解説します。',
    category: '製造業',
    tags: ['メンテナンス', '機械', 'トラブルシューティング'],
    views: 980,
    likes: 41,
    duration: 1100,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 4,
    userName: 'メンテナンス技師 三郎',
    isPublic: true,
    viewCount: 980,
    likeCount: 41,
    videoUrl: sampleVideoUrls[4 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video5/640/360`,
  },
  {
    id: 6,
    title: 'コミュニケーションスキル - チームワークの向上',
    description: '多様な背景を持つチームでの効果的なコミュニケーション方法を学びます。',
    category: '教育',
    tags: ['コミュニケーション', 'チームワーク', 'スキル'],
    views: 720,
    likes: 28,
    duration: 950,
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 2,
    userName: '教育者 花子',
    isPublic: true,
    viewCount: 720,
    likeCount: 28,
    videoUrl: sampleVideoUrls[5 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video6/640/360`,
  },
  {
    id: 7,
    title: '効率的な作業フローの設計',
    description: '製造現場での作業効率を向上させるフロー設計のポイントを解説します。',
    category: '製造業',
    tags: ['効率化', 'フロー設計', '製造'],
    views: 1340,
    likes: 52,
    duration: 1300,
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 3,
    userName: '品質管理者 次郎',
    isPublic: true,
    viewCount: 1340,
    likeCount: 52,
    videoUrl: sampleVideoUrls[6 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video7/640/360`,
  },
  {
    id: 8,
    title: '環境に配慮した製造プロセス',
    description: '持続可能な製造プロセスの実現に向けた取り組みを紹介します。',
    category: '環境',
    tags: ['環境', '持続可能性', '製造'],
    views: 650,
    likes: 24,
    duration: 1000,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 5,
    userName: '環境管理者 四郎',
    isPublic: true,
    viewCount: 650,
    likeCount: 24,
    videoUrl: sampleVideoUrls[7 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video8/640/360`,
  },
  {
    id: 9,
    title: '電気配線の基礎と安全対策',
    description: '電気工事における基本的な配線技術と安全に作業するための重要なポイントを解説します。',
    category: '電気工事',
    tags: ['電気', '配線', '安全', '工事'],
    views: 1890,
    likes: 92,
    duration: 1800,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 1,
    userName: '技術者 太郎',
    isPublic: true,
    viewCount: 1890,
    likeCount: 92,
    videoUrl: sampleVideoUrls[8 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video9/640/360`,
  },
  {
    id: 10,
    title: '建設現場での安全確認手順',
    description: '建設現場で必須となる安全確認の手順とチェックリストを詳しく説明します。',
    category: '建設',
    tags: ['建設', '安全', '確認手順'],
    views: 2340,
    likes: 108,
    duration: 1400,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 2,
    userName: '教育者 花子',
    isPublic: true,
    viewCount: 2340,
    likeCount: 108,
    videoUrl: sampleVideoUrls[9 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video10/640/360`,
  },
  {
    id: 11,
    title: 'プラスチック成形の基本技術',
    description: '射出成形やブロー成形など、プラスチック成形の基本技術を実演しながら解説します。',
    category: '製造業',
    tags: ['成形', 'プラスチック', '製造技術'],
    views: 1120,
    likes: 67,
    duration: 1650,
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 3,
    userName: '品質管理者 次郎',
    isPublic: true,
    viewCount: 1120,
    likeCount: 67,
    videoUrl: sampleVideoUrls[10 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video11/640/360`,
  },
  {
    id: 12,
    title: '外国人技能実習生への日本語教育',
    description: '技能実習生が現場で使える実践的な日本語表現とコミュニケーション方法を紹介します。',
    category: '教育',
    tags: ['日本語', '教育', '技能実習', 'コミュニケーション'],
    views: 2780,
    likes: 145,
    duration: 2200,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 2,
    userName: '教育者 花子',
    isPublic: true,
    viewCount: 2780,
    likeCount: 145,
    videoUrl: sampleVideoUrls[11 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video12/640/360`,
  },
  {
    id: 13,
    title: 'CNC工作機械の操作方法',
    description: 'CNC工作機械の基本的な操作方法とプログラミングの基礎を実演で解説します。',
    category: '製造業',
    tags: ['CNC', '工作機械', 'プログラミング', '製造'],
    views: 1450,
    likes: 89,
    duration: 1950,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 4,
    userName: 'メンテナンス技師 三郎',
    isPublic: true,
    viewCount: 1450,
    likeCount: 89,
    videoUrl: sampleVideoUrls[12 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video13/640/360`,
  },
  {
    id: 14,
    title: '食品製造における衛生管理',
    description: '食品製造現場での衛生管理の重要性と具体的な管理方法を詳しく説明します。',
    category: '食品製造',
    tags: ['食品', '衛生管理', '安全', '製造'],
    views: 3200,
    likes: 178,
    duration: 1600,
    createdAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 5,
    userName: '環境管理者 四郎',
    isPublic: true,
    viewCount: 3200,
    likeCount: 178,
    videoUrl: sampleVideoUrls[13 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video14/640/360`,
  },
  {
    id: 15,
    title: '溶接技術の上級テクニック',
    description: '熟練技術者が実践する高度な溶接テクニックと品質向上のコツを伝授します。',
    category: '製造業',
    tags: ['溶接', '上級技術', '品質向上'],
    views: 980,
    likes: 56,
    duration: 2400,
    createdAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 1,
    userName: '技術者 太郎',
    isPublic: true,
    viewCount: 980,
    likeCount: 56,
    videoUrl: sampleVideoUrls[14 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video15/640/360`,
  },
  {
    id: 16,
    title: '多文化チームでの協働作業',
    description: '異なる文化背景を持つメンバーとの効果的な協働作業の進め方を実例で紹介します。',
    category: '教育',
    tags: ['多文化', 'チームワーク', '協働', 'コミュニケーション'],
    views: 1650,
    likes: 94,
    duration: 1750,
    createdAt: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 2,
    userName: '教育者 花子',
    isPublic: true,
    viewCount: 1650,
    likeCount: 94,
    videoUrl: sampleVideoUrls[15 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video16/640/360`,
  },
  {
    id: 17,
    title: '塗装技術の基礎と応用',
    description: '工業製品の塗装における基本的な技術から応用テクニックまで幅広く解説します。',
    category: '製造業',
    tags: ['塗装', '技術', '応用', '製造'],
    views: 890,
    likes: 43,
    duration: 1200,
    createdAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 3,
    userName: '品質管理者 次郎',
    isPublic: true,
    viewCount: 890,
    likeCount: 43,
    videoUrl: sampleVideoUrls[16 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video17/640/360`,
  },
  {
    id: 18,
    title: '機械の定期点検とメンテナンス',
    description: '製造機械の定期点検の重要性と効率的なメンテナンススケジュールの立て方を説明します。',
    category: '製造業',
    tags: ['点検', 'メンテナンス', '機械', '定期'],
    views: 2100,
    likes: 112,
    duration: 1500,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 4,
    userName: 'メンテナンス技師 三郎',
    isPublic: true,
    viewCount: 2100,
    likeCount: 112,
    videoUrl: sampleVideoUrls[17 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video18/640/360`,
  },
  {
    id: 19,
    title: 'リサイクルと廃棄物管理',
    description: '製造現場でのリサイクル推進と適切な廃棄物管理の方法を実践的に解説します。',
    category: '環境',
    tags: ['リサイクル', '廃棄物', '環境', '管理'],
    views: 1340,
    likes: 78,
    duration: 1300,
    createdAt: new Date(Date.now() - 33 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 5,
    userName: '環境管理者 四郎',
    isPublic: true,
    viewCount: 1340,
    likeCount: 78,
    videoUrl: sampleVideoUrls[18 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video19/640/360`,
  },
  {
    id: 20,
    title: '工具の正しい選び方と使い方',
    description: '作業に適した工具の選び方と安全で効率的な使用方法を実演で説明します。',
    category: '製造業',
    tags: ['工具', '選び方', '使い方', '安全'],
    views: 2760,
    likes: 156,
    duration: 1100,
    createdAt: new Date(Date.now() - 36 * 24 * 60 * 60 * 1000).toISOString(),
    userId: 1,
    userName: '技術者 太郎',
    isPublic: true,
    viewCount: 2760,
    likeCount: 156,
    videoUrl: sampleVideoUrls[19 % sampleVideoUrls.length],
    thumbnailUrl: `https://picsum.photos/seed/video20/640/360`,
  },
]

// Mock users data
export const mockUsers: MockUser[] = [
  { id: 1, name: '技術者 太郎', email: 'taro@example.com' },
  { id: 2, name: '教育者 花子', email: 'hanako@example.com' },
  { id: 3, name: '品質管理者 次郎', email: 'jiro@example.com' },
  { id: 4, name: 'メンテナンス技師 三郎', email: 'saburo@example.com' },
  { id: 5, name: '環境管理者 四郎', email: 'shiro@example.com' },
]

// Mock comments data
export const mockComments: Record<number, MockComment[]> = {
  1: [
    {
      id: 1,
      content: 'とても参考になりました！',
      userId: 2,
      userName: '教育者 花子',
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 5,
    },
    {
      id: 2,
      content: '実践的な内容で助かります。',
      userId: 3,
      userName: '品質管理者 次郎',
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 3,
    },
  ],
  2: [
    {
      id: 3,
      content: '多言語対応の重要性がよくわかりました。',
      userId: 1,
      userName: '技術者 太郎',
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 4,
    },
  ],
  9: [
    {
      id: 4,
      content: '電気配線の基礎がよく理解できました。',
      userId: 2,
      userName: '教育者 花子',
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 8,
    },
  ],
  10: [
    {
      id: 5,
      content: '安全確認の重要性を再認識しました。',
      userId: 3,
      userName: '品質管理者 次郎',
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 6,
    },
  ],
  12: [
    {
      id: 6,
      content: '日本語教育の実践的な方法が参考になります。',
      userId: 1,
      userName: '技術者 太郎',
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 12,
    },
    {
      id: 7,
      content: '技能実習生の教育に活用したいです。',
      userId: 4,
      userName: 'メンテナンス技師 三郎',
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 7,
    },
  ],
  14: [
    {
      id: 8,
      content: '衛生管理の重要性がよくわかりました。',
      userId: 1,
      userName: '技術者 太郎',
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 15,
    },
  ],
  20: [
    {
      id: 9,
      content: '工具の選び方が参考になりました。',
      userId: 2,
      userName: '教育者 花子',
      createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      likes: 9,
    },
  ],
}

// Check if we should use mock data
export const shouldUseMockData = (): boolean => {
  if (typeof window === 'undefined') return false
  // 環境変数で強制的にmockデータを使う設定がある場合はtrueを返す
  if (process.env.NEXT_PUBLIC_USE_MOCK_DATA === 'true') {
    return true
  }
  const apiUrl = process.env.NEXT_PUBLIC_API_BASE_URL || ''
  // 開発環境（localhost）では常にmockデータを使用
  // 本番環境でもAPI URLが設定されていない場合はmockデータを使用
  return !apiUrl || apiUrl.includes('localhost') || apiUrl === '' || !apiUrl.startsWith('http')
}

